name = "nextli-vibecode"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "nextli-db"
database_id = "6d4d4e43-c223-460a-81db-faf8976e148a"

[vars]
JWT_SECRET = "REPLACE_WITH_SECRET"
